### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by curtisblackwell** [itmecho/atom-phpunit#1]
This isn't at all a big deal, but running within an anonymous function throws an error.

1. Create a method that contains an anonymous function.
2. Place cursor within the anonymous function.
3. Use Run Test method.

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [atom-phpunit](https://github.com/Synapse791/atom-phpunit) package 1.2.0

### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At /Users/curtisblackwell/.atom/packages/atom-phpunit/lib/atom-phpunit.js:142

TypeError: Cannot read property '1' of null
    at Object.getFunctionName (/packages/atom-phpunit/lib/atom-phpunit.js:142:51)
    at Object.runTest (/packages/atom-phpunit/lib/atom-phpunit.js:65:17)
    at /packages/atom-phpunit/lib/atom-phpunit.js:42:43)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:55.6.0 autocomplete-plus:confirm (input.hidden-input)
     -0:49.5.0 editor:select-to-end-of-line (input.hidden-input)
     -0:49.2.0 core:backspace (input.hidden-input)
     -0:47.5.0 core:move-left (input.hidden-input)
     -0:46.6.0 core:move-right (input.hidden-input)
     -0:43.3.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:43.3.0 docblockr:parse-enter (input.hidden-input)
     -0:43.3.0 editor:newline (input.hidden-input)
     -0:43.2.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:43.2.0 docblockr:parse-enter (input.hidden-input)
     -0:43.2.0 editor:newline (input.hidden-input)
  2x -0:41.3.0 autocomplete-plus:confirm (input.hidden-input)
     -0:22.2.0 core:save (input.hidden-input)
     -0:16.4.0 atom-phpunit:run-test (input.hidden-input)
     -0:11.7.0 core:move-up (input.hidden-input)
     -0:11 atom-phpunit:run-test (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.5 
aligner 0.22.3 
aligner-css 1.2.0 
aligner-javascript 1.0.0 
aligner-php 1.0.0 
aligner-scss 1.1.0 
an-old-hope-syntax 1.0.2 
atom-alignment 0.12.1 
atom-phpunit 1.2.0 
autocomplete-php 0.3.7 
blade-snippets 0.2.0 
comment-headers 2.15.0 
css-comb 2.5.0 
docblockr 0.9.1 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.0.15 
hyperclick 0.0.40 
intentions 1.1.2 
language-antlers 0.3.4 
language-apache 1.7.0 
language-blade 0.28.1 
language-dotenv 1.0.0 
language-vue 0.21.2 
laravel 0.7.1 
less-than-slash 0.16.0 
linter 1.11.23 
linter-htmlhint 1.3.2 
linter-js-yaml 1.2.7 
linter-jscs 4.1.1 
linter-jsonlint 1.3.0 
linter-phpcs 1.5.9 
linter-sass-lint 1.7.4 
linter-tidy 2.3.0 
php-integrator-annotations 1.1.1 
php-integrator-autocomplete-plus 1.2.0 
php-integrator-base 2.1.10 
php-integrator-call-tips 1.2.1 
php-integrator-linter 1.3.0 
php-integrator-navigation 1.1.2 
php-integrator-refactoring 1.3.1 
php-integrator-tooltips 1.1.5 
pigments 0.39.0 
pretty-json 1.6.1 
project-manager 3.3.3 
sort-lines 0.14.0 
wakatime 6.0.13 
```

**Comment by curtisblackwell** [comment]
Actually, appears it happens when the cursor comes after the anonymous function, too.

**Comment by itmecho** [comment]
Good spot! I'll take a look at this ASAP. I have a fix in mind.

**Comment by itmecho** [comment]
@curtisblackwell Can you confirm this is fixed in [v1.2.1](https://github.com/Synapse791/atom-phpunit/releases/tag/v1.2.1)? I have tested using some dummy tests but it would be good for you to confirm it's working for you and close the issue. Thanks for the super detailed report btw :smiley:

**Comment by curtisblackwell** [comment]
I can confirm 1.2.1 fixes it. Thanks!

I didn't exactly have to do much for that report… Just used the "Report issue" button that Atom provides when you encounter an error.

**Comment by itmecho** [comment]
Perfect, Thanks!

Ah that's cool. Good old Github :grin:
